# 导包

In [1]:
import numpy as np

# 创建数组对象 - ndarray
- 列表方式创建ndarray
- 函数方式创建ndarray - [重点]

In [2]:
np.__version__  # 查看ndarray的版本

'1.13.3'

In [4]:
na1 = np.array([1, 2, 3, 4])
na1

array([1, 2, 3, 4])

# 在numpy中，数组中元素的类型是统一的
## 如果元素类型不统计，则按(左高右低) str->float -> int 优先级转换统一类型

In [6]:
na2 = np.array(['A', 'B', 10, 9, 'D']) 
na3 = np.array([10, 20, 30, 10.95, 9.75, 40.5])
# na2  # 默认不会显示，可以使用display(变量名)来显示
# na3 
display(na2)  
display(na3)

array(['A', 'B', '10', '9', 'D'],
      dtype='<U2')

array([ 10.  ,  20.  ,  30.  ,  10.95,   9.75,  40.5 ])

## 在创建数组时，可以通过dtype指定数组的类型

In [10]:
# na4 = np.array([1, '2.0', 'A', 10.5], dtype=np.str)
na4 = np.array([1, 2, 9.5, 10.5], dtype=np.int)
na4

array([ 1,  2,  9, 10])

# 在创建数组时，可以通过ndmin指定数组的维度

In [11]:
na5 = np.array([[1, 2], [3, 4]])
na5

array([[1, 2],
       [3, 4]])

In [14]:
# ndmin 指定数组的维度
# 注： 不能少于当前指定list的维度，只能大于或等于，如果小于时，则不变
na6 = np.array([[1, 2, 5], [3, 4, 9]], ndmin=3)
na6

array([[[1, 2, 5],
        [3, 4, 9]]])

# 函数方式创建ndarray数组
- np.ones(shape, dtype) 创建元素都是1的shape形状的数组 

In [17]:
# shape是一个元组类型
np.ones((320,480), dtype=int)  # 默认为float小数类型

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ..., 
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

- full(shape, full_value, dtype) 创建指定fill_value元素的shape形状的数组

In [23]:
# np.full((2, 3), 0)  # 数组的类型默认为fill_value的类型
np.full((2, 3, 2), 'A')

array([[['A', 'A'],
        ['A', 'A'],
        ['A', 'A']],

       [['A', 'A'],
        ['A', 'A'],
        ['A', 'A']]],
      dtype='<U1')

- eye(N, M, k=0) 
  - 对角线上的元素全为1的数组,其余的全是0， 
  - N表行，M表示列，M为None时使用N表示列
  - k为0时，1在对角线上， 大于0时，对角线向上平移，小于0时，对角线向下平移

In [25]:
np.eye(4, dtype=int)  # 默认为float

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [27]:
np.eye(4, k=1, dtype=int) # 1的元素向上平移1个单位

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [28]:
np.eye(4, k=-1, dtype=int) # 1的元素向下平移1个单位

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

- np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
   - 生成一个等差数列
   - start,stop是起始和结束的数值
   - num 数列的大小，每两个元素的差值均相同
   - endpoint=True 表示最大到stop值
   - retstep=False, 是否显示差值

In [35]:
na, step = np.linspace(1, 11, num=10,endpoint=False, dtype=int, retstep=True)
display(na, step)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

1.0

- np.arange([start, ]stop, [step, ]dtype=None)
  - 可指定步长， step 默认为1
  - 在[start, stop) 范围内，生成step步长的数列
  - start可选，默认为0

In [36]:
np.arange(10)  # 生成0到9的步长为1的等差数列

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 生成【1, 100】之间的50个等差数列

In [39]:
np.linspace(1, 100, num=50, dtype=int)

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [45]:
np.arange(1, 100, step=2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

# 随机产生的数组
- np.random.random(size=None) 随机产生[0,1)之间小数
  - size表示数组的形状或大小, 是元组或int类型
- np.random.randint(low, high=None, size=None, dtype='l')
  - 随机产生的是[low, high]之间的整数
  - dtype默认为long长整型
- np.random.randn(d0, d1, ..., dn) 正态分布的数
  - d0, d1 表示的是维度

In [46]:
np.random.random()  # 返回一个随机数

0.34914624826764784

In [47]:
np.random.random(size=10) # 随机产生10个[0，1）之间小数

array([ 0.83001864,  0.72108582,  0.45788621,  0.48031992,  0.50264929,
        0.38324774,  0.40671282,  0.83487619,  0.32345224,  0.4360225 ])

In [48]:
np.random.random((2, 3)) # 生成2行3列的二维数组

array([[ 0.12697442,  0.98095388,  0.9864822 ],
       [ 0.96598151,  0.10573995,  0.89083271]])

In [49]:
np.random.randint(1, 10, size=(3, 3)) 
# ?MySQL数据库中的索引index如何存储的

array([[6, 3, 5],
       [2, 5, 9],
       [3, 2, 2]])

In [51]:
np.random.randn(10, 3)  # 正太分布的数值, 数值范围[-pi, pi] 

array([[-1.33741367,  0.64498795,  0.32371129],
       [-0.93561603, -1.02490157, -0.72219804],
       [ 1.15684329, -3.01350294, -0.88642081],
       [-1.16628599, -0.01228814,  0.87317969],
       [-0.94513406, -0.55859409,  0.72039431],
       [ 1.31718805, -2.22476348, -1.50808356],
       [ 0.0634834 ,  2.0073576 , -0.08822304],
       [ 0.25418865,  1.36358252, -1.52325912],
       [ 0.78566796, -0.35076573, -1.3584293 ],
       [-0.66275549, -1.3521411 , -0.04274087]])

- np.random.seed(seed=None)  设置随机的种子
    
    说明： 设置了特定的随机种子seed，以后每次随机产生的数是一样的。

In [52]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [55]:
np.random.seed(2)
np.random.random(size=(2, 2))

array([[ 0.4359949 ,  0.02592623],
       [ 0.54966248,  0.43532239]])

In [76]:
display(np.random.random())

0.025926231827891333

- np.random.normal(loc=0.0, scale=1.0, size=None)

    默认返回正态分布的数列，loc期望值， scale方差

In [87]:
np.random.normal(size=(2, 3))

array([[-0.02330375,  0.84177767,  1.36758552],
       [ 0.57470769, -1.88576241,  0.17092537]])

In [88]:
# 高斯分布
np.random.normal(1, scale=1.5, size=(2, 3))

array([[ 0.39536003,  3.45644273,  0.09205323],
       [-1.39162261,  2.36781046, -1.16576233]])

# ndarray的属性
- size 数量
- shape 形状
- dtype 类型
- ndim  维度

1. 创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [100]:
a = np.zeros(10, dtype=int)
a[4] = 1  # 数组的索引
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [97]:
a1 = np.zeros((2, 3), dtype=np.int8)
a1

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [98]:
display(a1.size, a1.shape, a1.dtype, a1.ndim)

6

(2, 3)

dtype('int8')

2