# 索引操作

In [3]:
import numpy as np

- 一维数组

In [4]:
# 2. 创建一维数组，元素从10到49的ndarray对象
a1 = np.arange(10, 50)
a2 = np.random.randint(10, 50,size=10)
display(a1, a2)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

array([23, 33, 15, 31, 33, 49, 17, 25, 27, 25])

In [6]:
a2[1] = 0
display(a2[1], a2[2])

0

15

In [8]:
# 可以同时修改多个索引的位置数据
a2[[1, 2, 5]] = [10, 21, 0]
display(a2[[1, 2, 5]], a2)

array([10, 21,  0])

array([23, 10, 21, 31, 33,  0, 17, 25, 27, 25])

- 二维数组的索引操作

In [12]:
a3 = np.random.rand(2, 3)  # 生成[0, 1)之间
a3

array([[ 0.59352611,  0.61692857,  0.54422851],
       [ 0.54774835,  0.40426295,  0.96087479]])

In [13]:
# 修改第一行第二列的数值为 1
a3[0][1] = 1
a3

array([[ 0.59352611,  1.        ,  0.54422851],
       [ 0.54774835,  0.40426295,  0.96087479]])

In [14]:
# 修改第2行第1列的数值为1.5
a3[1, 0] = 1.5
a3

array([[ 0.59352611,  1.        ,  0.54422851],
       [ 1.5       ,  0.40426295,  0.96087479]])

In [17]:
# 同时修改
# 1)第1行第1、2列的数值为 0.5和0.6
# 2)第2行第2、3列的数值为 0.66和0.88
# 【建议】使用以下方式：
a3[0][[0,1]] = [0.5, 0.6]
a3[1][[1, 2]] = [0.66, 0.88]
a3

array([[ 0.5       ,  0.6       ,  0.54422851],
       [ 1.5       ,  0.66      ,  0.88      ]])

In [20]:
a3 = np.random.rand(2, 3)
display(a3)
a3[[0, 1], [[0,1],[1,2]]] = [[0.5, 0.66],[0.6, 0.88]]
a3

array([[ 0.52316731,  0.26774701,  0.4121496 ],
       [ 0.09981525,  0.5785048 ,  0.89032383]])

array([[ 0.5       ,  0.6       ,  0.4121496 ],
       [ 0.09981525,  0.66      ,  0.88      ]])

# 切片操作

- 行切片  a[start:end] , 不包含end行

In [22]:
a4 = np.eye(4)
a4

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [23]:
# 显示前2行
a4[:2]

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.]])

In [24]:
# 显示最后2行
a4[-2:]

array([[ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

- 列切片 n[:, start:end]  不包含end

In [26]:
# 显示第2，3列的数据
a4[:,1:3]

array([[ 0.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  0.]])

In [27]:
a5 = np.random.randint(10, 100, size=(6, 6))
a5

array([[98, 72, 69, 90, 27, 40],
       [47, 82, 14, 29, 82, 29],
       [24, 78, 27, 66, 35, 55],
       [99, 98, 48, 70, 19, 56],
       [68, 74, 77, 77, 42, 56],
       [96, 41, 90, 20, 57, 85]])

In [33]:
# 查看第1~2列和第5-6列
a5[:,[0,1,4,5]]

array([[98, 72, 27, 40],
       [47, 82, 82, 29],
       [24, 78, 35, 55],
       [99, 98, 19, 56],
       [68, 74, 42, 56],
       [96, 41, 57, 85]])

In [34]:
# 查看第2-5行的，第3-5列
a5[1:5, 2:5]

array([[14, 29, 82],
       [27, 66, 35],
       [48, 70, 19],
       [77, 77, 42]])

In [35]:
# 查看第2、4、5行的第1、3、5列的数值
a5[[1,3,4], [0,2,4]]

array([47, 48, 42])

# 数组变形 
- array_obj.reshape(size) 变形之后的元素的个数不变

In [36]:
a6 = np.arange(10, 20) # 生成[10, 19]的范围的10个数
a6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
a6.size

10

In [38]:
a6.reshape((10,1))

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [39]:
a6.reshape((5, 2))  # 5行2列

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [40]:
# 矩阵转置
a7 = np.array([[1,2,3], [4,5,6], [7,8,9]])
a7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
a7.T  # 转置

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
a7.transpose()  # 转置

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

扩展： SQL语句-if()函数和group by分组及join连表查询

# 级联操作

In [44]:
a8 = np.array([[1,2], [3,4]])
a9 = np.array([[8,9], [10, 12]])
display(a8, a9)

array([[1, 2],
       [3, 4]])

array([[ 8,  9],
       [10, 12]])

In [45]:
np.concatenate((a8, a9), axis=0)  # 按垂直方向（以行方式）

array([[ 1,  2],
       [ 3,  4],
       [ 8,  9],
       [10, 12]])

In [46]:
np.concatenate((a8, a9), axis=1) # 按水平方向(以列的方式)

array([[ 1,  2,  8,  9],
       [ 3,  4, 10, 12]])

In [47]:
np.vstack((a8, a9)) # 垂直级联

array([[ 1,  2],
       [ 3,  4],
       [ 8,  9],
       [10, 12]])

In [48]:
np.hstack((a8, a9))

array([[ 1,  2,  8,  9],
       [ 3,  4, 10, 12]])

# 切分
- split(array, indices_or_section, axis=0)
- hsplit() 水平切分
- vsplit() 垂直切分

In [49]:
a10 = np.arange(1, 10).reshape((3,3))
a10

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
# axis=0,行切分
np.split(a10, [1, 2])  # 将第2列切出来

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [57]:
np.vsplit(a10,[1,2])  # 垂直切分

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [55]:
# axis=1， 列切分
np.split(a10, [1,2], axis=1)

[array([[1],
        [4],
        [7]]), array([[2, 3],
        [5, 6],
        [8, 9]])]

In [58]:
np.hsplit(a10, [1,2])  # 水平切分，列切分

[array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]]), array([[3],
        [6],
        [9]])]

In [59]:
a11 = a10.copy()  # 创建ndarray的副本
a11[0,0] = 100
a11

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [60]:
a10

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

练习： 创建两个三维的数组，按不同的坐标轴axis(0,1,2)进行级联操作

 练习： 创建一个3维的数组，按不同的坐标轴切出数据