# 聚合操作
- max() 最大值
- min() 最小值
- mean() 平均值
- sum()  计算总合
- std()  标准差

In [2]:
import numpy as np  # 数组计算
import pandas as pd  # 数据分析的工具

In [10]:
def mean(*args):
    """
    计算给定所有元素的平均值
    axis = 0, 1, 2
    [
     [[], [], []],
     [[], [], []],
     [[], [], []]
    ]
    """
    ary = np.array(list(args))  # ndarray类型
    if ary.ndim == 1:
        return np.mean(ary)  # numpy的求平均的函数
    elif ary.ndim == 2:
        return np.mean(ary, axis=1)

In [3]:
mean(1,2,3,4,5,6,7,8,9)

5.0

In [4]:
mean(10, 20)

15.0

In [11]:
mean([1,2],[3,4],[5,6],[7,8],[9,10])

array([ 1.5,  3.5,  5.5,  7.5,  9.5])

In [13]:
# 每一个一维数组表示一位同学的语文、数学 和英语的成绩
# 一维数组中的下标： 0 语文， 1数学, 2 英语
scores = [
    [100, 98, 99],
    [90, 100, 80],
    [91, 98, 95.5],
    [70, 75,  90]
]

sa = np.array(scores)
sa1 = np.mean(sa, axis=0)  # 计算每门课的平均成绩
print('数学的平均成绩:', sa1[1])

sa2 = np.mean(sa, axis=1)
print('第一位同学的平均成绩:', sa2[0])

数学的平均成绩: 92.75
第一位同学的平均成绩: 99.0


In [14]:
sa

array([[ 100. ,   98. ,   99. ],
       [  90. ,  100. ,   80. ],
       [  91. ,   98. ,   95.5],
       [  70. ,   75. ,   90. ]])

In [15]:
# 计算全班的总成绩
np.sum(sa)

1086.5

In [18]:
# 计算每个学科的总成绩
# np.sum(sa, axis=0).max()
np.sum(sa, axis=0)

array([ 351. ,  371. ,  364.5])

In [19]:
# 计算每人的总成绩
np.sum(sa, axis=1)

array([ 297. ,  270. ,  284.5,  235. ])

练习1: 计算每个人的最高成绩，最低成绩

In [20]:
display(np.max(sa,axis=1), sa.min(axis=1))

array([ 100.,  100.,   98.,   90.])

array([ 98.,  80.,  91.,  70.])

练习2: 计算每个学科的最高成绩，最低成绩

In [21]:
display(np.max(sa,axis=0), sa.min(axis=0))

array([ 100.,  100.,   99.])

array([ 70.,  75.,  80.])

扩展： 读取csv文件